// Command stopwatch is a Lottie-driven stopwatch UI. Every visual element
// is a Lottie animation:
//
//   - Digits are cartoon text morphs (digit-N.json shows N at frame 0 and
//     plays an exaggerated launch-and-bounce to N+1), generated by ./gen.
//   - The colon does a squishy pulse once per second while running.
//   - Buttons play a press pop with a particle burst on click.
//
// Text renders in "Luckiest Guy" (Apache-2.0), bundled next to the assets.
//
// Usage:
//
//	go run ./examples/lottie/stopwatch
//
// Click START/STOP/RESET (or press space / R).
package main

import (
	"bytes"
	"embed"
	"fmt"
	"image/color"
	"log"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
	"github.com/hajimehoshi/ebiten/v2/text/v2"

	lottie "github.com/shibukawa/lottie-go"
)

//go:embed assets/*.json assets/*.ttf
var assets embed.FS

const (
	digitScale = 0.8
	digitW     = 160 * digitScale
	digitH     = 220 * digitScale
	sepW       = 60 * digitScale
	faceTop    = 30.0
	screenW    = 640
	screenH    = 330
)

// digitCell shows one digit. It keeps one player per transition animation;
// the player for digit N held at frame 0 displays N, and playing it runs
// the N -> N+1 morph.
type digitCell struct {
	value   int
	players [10]*lottie.Player
	current *lottie.Player
}

func newDigitCell(anims *[10]*lottie.Animation) *digitCell {
	c := &digitCell{}
	for i, a := range anims {
		c.players[i] = a.NewPlayer()
		c.players[i].Pause()
	}
	c.current = c.players[0]
	return c
}

func (c *digitCell) set(v int) {
	if v == c.value {
		return
	}
	if v == (c.value+1)%10 {
		// Successor: play the morph from the old digit.
		c.current = c.players[c.value]
		c.current.Seek(0)
		c.current.Play()
	} else {
		// Jump (e.g. reset, 5 -> 0 rollover): snap to the new digit.
		c.current = c.players[v]
		c.current.Seek(0)
		c.current.Pause()
	}
	c.value = v
}

func (c *digitCell) update() { c.current.Update() }

func (c *digitCell) draw(dst *ebiten.Image, x, y float64) {
	var opts lottie.DrawOptions
	opts.GeoM.Scale(digitScale, digitScale)
	opts.GeoM.Translate(x, y)
	c.current.Draw(dst, &opts)
}

// button is a clickable Lottie animation.
type button struct {
	player     *lottie.Player
	x, y, w, h float64
}

func (b *button) hit(mx, my int) bool {
	fx, fy := float64(mx), float64(my)
	return fx >= b.x && fx < b.x+b.w && fy >= b.y && fy < b.y+b.h
}

func (b *button) press() {
	b.player.Seek(0)
	b.player.Play()
}

func (b *button) draw(dst *ebiten.Image) {
	var opts lottie.DrawOptions
	opts.GeoM.Scale(b.w/240, b.h/90)
	opts.GeoM.Translate(b.x, b.y)
	b.player.Draw(dst, &opts)
}

type game struct {
	digits [4]*digitCell // M M : S S
	colon  *lottie.Player

	startBtn *button
	stopBtn  *button
	resetBtn *button

	running bool
	elapsed time.Duration
	last    time.Time
}

// toggle flips run state. The press animation plays on the button that is
// visible after the flip (START and STOP swap in place on click).
func (g *game) toggle() {
	if g.running {
		g.elapsed += time.Since(g.last)
		g.running = false
		g.colon.Pause()
		g.startBtn.press()
	} else {
		g.last = time.Now()
		g.running = true
		g.colon.Play()
		g.stopBtn.press()
	}
}

func (g *game) reset() {
	g.running = false
	g.elapsed = 0
	g.colon.Pause()
	g.colon.Seek(0)
	g.resetBtn.press()
}

func (g *game) Update() error {
	if inpututil.IsMouseButtonJustPressed(ebiten.MouseButtonLeft) {
		mx, my := ebiten.CursorPosition()
		switch {
		case g.startBtn.hit(mx, my):
			g.toggle()
		case g.resetBtn.hit(mx, my):
			g.reset()
		}
	}
	if inpututil.IsKeyJustPressed(ebiten.KeySpace) {
		g.toggle()
	}
	if inpututil.IsKeyJustPressed(ebiten.KeyR) {
		g.reset()
	}

	total := g.elapsed
	if g.running {
		total += time.Since(g.last)
	}
	if max := 100*time.Minute - time.Second; total > max {
		total = max
	}
	// Total seconds -> MM:SS digit values.
	sec := int(total / time.Second)
	m := sec / 60
	s := sec % 60
	vals := [4]int{m / 10 % 10, m % 10, s / 10, s % 10}
	for i, c := range g.digits {
		c.set(vals[i])
		c.update()
	}
	g.colon.Update()
	g.startBtn.player.Update()
	g.stopBtn.player.Update()
	g.resetBtn.player.Update()
	return nil
}

func (g *game) Draw(screen *ebiten.Image) {
	screen.Fill(color.RGBA{0x1d, 0x35, 0x6e, 0xff}) // deep sky blue

	x := (screenW - (4*digitW + sepW)) / 2
	for i, c := range g.digits {
		c.draw(screen, x, faceTop)
		x += digitW
		if i == 1 { // colon between minutes and seconds
			var opts lottie.DrawOptions
			opts.GeoM.Scale(digitScale, digitScale)
			opts.GeoM.Translate(x, faceTop)
			g.colon.Draw(screen, &opts)
			x += sepW
		}
	}

	if g.running {
		g.stopBtn.x = g.startBtn.x
		g.stopBtn.y = g.startBtn.y
		g.stopBtn.draw(screen)
	} else {
		g.startBtn.draw(screen)
	}
	g.resetBtn.draw(screen)
}

func (g *game) Layout(w, h int) (int, int) { return screenW, screenH }

func load(name string, resolver lottie.FontResolver) *lottie.Animation {
	data, err := assets.ReadFile("assets/" + name)
	if err != nil {
		log.Fatal(err)
	}
	anim, err := lottie.Decode(bytes.NewReader(data))
	if err != nil {
		log.Fatalf("%s: %v", name, err)
	}
	if resolver != nil {
		anim.SetFontResolver(resolver)
	}
	if unsup := anim.UnsupportedFeatures(); len(unsup) > 0 {
		log.Printf("%s: unsupported %v", name, unsup)
	}
	return anim
}

func main() {
	ttf, err := assets.ReadFile("assets/LuckiestGuy-Regular.ttf")
	if err != nil {
		log.Fatal(err)
	}
	src, err := text.NewGoTextFaceSource(bytes.NewReader(ttf))
	if err != nil {
		log.Fatal(err)
	}
	resolver := func(family, style string) *text.GoTextFaceSource { return src }

	var digitAnims [10]*lottie.Animation
	for i := 0; i < 10; i++ {
		digitAnims[i] = load(fmt.Sprintf("digit-%d.json", i), resolver)
	}
	g := &game{}
	for i := range g.digits {
		g.digits[i] = newDigitCell(&digitAnims)
	}
	colonAnim := load("colon.json", nil)
	g.colon = colonAnim.NewPlayer()
	g.colon.SetLoop(true)
	g.colon.Pause()

	const btnY = 240
	g.startBtn = &button{player: load("button-START.json", resolver).NewPlayer(), x: 140, y: btnY, w: 170, h: 64}
	g.stopBtn = &button{player: load("button-STOP.json", resolver).NewPlayer(), x: 140, y: btnY, w: 170, h: 64}
	g.resetBtn = &button{player: load("button-RESET.json", resolver).NewPlayer(), x: 330, y: btnY, w: 170, h: 64}
	for _, b := range []*button{g.startBtn, g.stopBtn, g.resetBtn} {
		b.player.Pause()
		b.player.Seek(0)
	}

	ebiten.SetWindowSize(screenW*2, screenH*2)
	ebiten.SetWindowTitle("lottie-go stopwatch")
	if err := ebiten.RunGame(g); err != nil {
		log.Fatal(err)
	}
}
